# Generated by Django 5.1.3 on 2024-12-04 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descarga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'stocks',
                'db_table': 'grifo_stock',
            },
        ),
        migrations.CreateModel(
            name='Surtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'surtidores',
                'db_table': 'grifo_surtidores',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('D', 'Día'), ('N', 'Noche')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'turnos',
                'db_table': 'grifo_turnos',
            },
        ),
        migrations.CreateModel(
            name='ContadorSurtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contador_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_final', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('surtidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.surtidor')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.turno')),
            ],
            options={
                'verbose_name_plural': 'contadores por surtidor',
                'db_table': 'grifo_contadores_surtidor',
            },
        ),
    ]
