# Generated by Django 4.1.13 on 2024-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_task_created_at_task_done"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadTransporte",
            fields=[
                ("id_transporte", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numero_unidad",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("socio", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Unidades de Transporte",
                "db_table": "unidades_transporte",
            },
        ),
    ]
