# Generated by Django 5.0.6 on 2024-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_unidadtransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtransporte',
            name='contacto',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='responsable',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
