# Generated by Django 5.0.6 on 2024-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_unidadtransporte_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtransporte',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='responsable',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
