# Generated by Django 5.0.6 on 2024-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_unidadtransporte_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadtransporte',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
