# Generated by Django 5.0.6 on 2024-07-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_unidadtransporte_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descarga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='responsable',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
