# Generated by Django 5.0.6 on 2024-07-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_stockrecord_alter_unidadtransporte_responsable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockRecord',
            new_name='Stock',
        ),
    ]
