# Generated by Django 5.0.6 on 2024-07-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_stockrecord_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
