# Generated by Django 5.0.6 on 2024-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_stock_options_alter_stock_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="diferencias",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
