# Generated by Django 5.0.6 on 2024-08-27 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_stock_diferencias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Surtidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "surtidores",
                "db_table": "surtidores",
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[("D", "Día"), ("N", "Noche")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "turnos",
                "db_table": "turnos",
            },
        ),
        migrations.CreateModel(
            name="ContadorSurtidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contador_inicial",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "contador_final",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "diferencias",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fecha_hora_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_hora_final", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surtidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.surtidor"
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.turno"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contadores por surtidor",
                "db_table": "contadores_surtidor",
            },
        ),
    ]
