# Generated by Django 5.1.3 on 2024-11-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_surtidor_turno_contadorsurtidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='controlUnidades',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('vuelta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vuelta', models.DateField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unidadtransporte')),
            ],
            options={
                'verbose_name_plural': 'control de unidades',
                'db_table': 'control_unidades',
            },
        ),
    ]
