# Generated by Django 5.1.3 on 2024-11-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_controlunidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarifa',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tarifa', models.TextField(default='personalizado', max_length=80)),
                ('monto', models.TextField(default='0.00', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'tarifa de unidades',
                'db_table': 'tarifa_unidades',
            },
        ),
    ]
