# Generated by Django 5.1.3 on 2024-11-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_unidadtransporte_id_tarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'metodos de pago',
                'db_table': 'metodo_pago',
            },
        ),
    ]
