# Generated by Django 5.1.3 on 2024-11-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlunidades',
            name='fecha_vuelta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
