# Generated by Django 5.0.6 on 2024-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_controlunidades_fecha_vuelta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('tipo_licencia', models.CharField(choices=[('allb', 'Microbuses o minibuses(allb) '), ('allla', 'Omnibuses urbanos(allla)'), ('alllb', 'Omnibuses interurbanos(alllb)')], default='Allb', max_length=60)),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'db_table': 'licencias',
                'ordering': ['fecha_expiracion'],
            },
        ),
    ]
