# Generated by Django 5.0.6 on 2024-11-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='numero_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='myapp.unidadtransporte'),
        ),
    ]
