# Generated by Django 5.1.3 on 2024-12-04 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_unidadtransporte_vencimiento_soat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contadorsurtidor',
            name='surtidor',
        ),
        migrations.RemoveField(
            model_name='contadorsurtidor',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='contadorsurtidor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='id_tarifa',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tarifa'),
        ),
        migrations.DeleteModel(
            name='Surtidor',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.DeleteModel(
            name='ContadorSurtidor',
        ),
    ]
