# Generated by Django 5.0.6 on 2024-12-26 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_contadorsurtidor_surtidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtransporte',
            name='placa',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2029, 12, 26)),
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='vencimiento_soat',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
