# Generated by Django 5.0.6 on 2024-12-26 17:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_unidadtransporte_placa_alter_licencia_fecha_emision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlunidades',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='vencimiento_civm',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
