# Generated by Django 5.0.6 on 2025-01-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_licencia_fecha_emision_and_more'),
        ('myapp', '0024_controlunidades_usuario_and_more'),
    ]

    operations = [
    ]
