# Generated by Django 5.0.6 on 2025-01-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_pagos_usuario_alter_licencia_fecha_expiracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadtransporte',
            name='id_tarifa',
        ),
    ]
