# Generated by Django 5.0.6 on 2025-01-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_merge_20250113_1805'),
        ('myapp', '0027_remove_unidadtransporte_id_tarifa'),
    ]

    operations = [
    ]
