# Generated by Django 5.0.6 on 2025-01-14 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_merge_20250114_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2030, 1, 14)),
        ),
    ]
