# Generated by Django 5.0.6 on 2025-01-15 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_licencia_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2030, 1, 15)),
        ),
    ]
