# Generated by Django 5.0.6 on 2025-01-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_licencia_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlunidades',
            name='vuelta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
