# Generated by Django 5.0.6 on 2025-01-16 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_controlunidades_vuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2030, 1, 16)),
        ),
    ]
