# Generated by Django 5.0.6 on 2025-01-21 13:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_licencia_fecha_expiracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Rutas',
                'db_table': 'rutas',
            },
        ),
        migrations.AlterModelOptions(
            name='metodo_pago',
            options={'verbose_name_plural': 'Metodos de Pago'},
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2030, 1, 21)),
        ),
        migrations.CreateModel(
            name='PagoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_vuelta', models.IntegerField(blank=True, null=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.metodo_pago')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unidadtransporte')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ruta')),
            ],
            options={
                'verbose_name_plural': 'Pagos Diarios',
                'db_table': 'pagos_diarios',
            },
        ),
        migrations.DeleteModel(
            name='pagos',
        ),
    ]
