# Generated by Django 5.0.6 on 2025-02-11 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_licencia_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2030, 2, 11)),
        ),
    ]
